### ISSUE TITLE
Tourist Dashboard receives data from backend

### ISSUE THREAD

**Issue by DanielWilliamParsons** [Team-Strawberry-CC36/frontend#29]
**THIS IS BACKEND AND FRONTEND**
The endpoint needs writing to collect data from the backend.
Interface is in frontend/src/utils/interfaces/PlacesVisited.ts.
It looks like this:
```
interface IPlaceVisitedAlias {
    placeId: number;
    placeName: string;
    placeType: string;
    experience: string;
    dateVisited: Date;
}

interface ApiResponsePlaceVisited<T> {
    message: string;
    data: T;
}

export type IPlacesVisited = ApiResponsePlaceVisited<IPlaceVisitedAlias[]> | null;
```

TouristDashboard contains fetchPlacesVisitedByUser function to connect with backend.
It needs uncommenting.
Component currently uses mock data. Replace mockPlacesVisitedByUser with placesVisitedByUser when database is ready.

**Comment by brianaqp** [comment]
@DanielWilliamParsons How is this going? :octocat:

**Comment by DanielWilliamParsons** [comment]
Slowly, but getting there. It's a learning curve for me, so please don't worry.
