### ISSUE TITLE
Make buttons work in tourist dashboard and implement badges

### ISSUE THREAD

**Issue by DanielWilliamParsons** [Team-Strawberry-CC36/frontend#30]
Buttons in tourist dashboard are:

- Logout (user should be able to log out from here)
- Search (user should be able to search - is this from this page or does this redirect to the home page?
- Edit (for each experience listed, the user should be able to edit their experience details. How would they do this? Route back to the experiences page for editing?)

Additionally, are we going to implement the badges system?

**Comment by brianaqp** [comment]
Right now, its completed bit the logount and the edit buttons.
