### ISSUE TITLE
Develop guides for every place

### ISSUE THREAD

**Issue by DanielWilliamParsons** [Team-Strawberry-CC36/frontend#38]

**Comment by brianaqp** [comment]
# Guides
Every place needs static information to help tourist in the most regular scenario

We need to do it for the tree places
- shrine
- onsen
- restaurants

**Comment by brianaqp** [comment]
Related to #66 

Is this finished? Or require more styling?

**Comment by brianaqp** [comment]
@ai-n0808

**Comment by ai-n0808** [comment]
@brianaqp I feel that’s finished it.
So as I asked you guys yesterday, I want to know everyone’s thoughts. 
But I think it should be finished it for now

**Comment by brianaqp** [comment]
okay. In the weekend we can style it.
