### ISSUE TITLE
Delete an experience in dashboard

### ISSUE THREAD

**Issue by brianaqp** [Team-Strawberry-CC36/frontend#71]
## The issue

Inside experiences by place, if I remove one experience, thats ok, it works. But if go back to the map, and I already have that place in my _state_ (pinia), it doesn't update the experiences.

So if I try to enter to see if my deletion was succesfull, to my place already in the state, i will see my "deleted" experience.

This is an error in terms of bad behavior, because the server its deleting experiences, but the frontend its not reacting as its supposed to.

## The task
Everytime the server confirms a deletion,  we need to update the `state` in pinia, to remove that experience of that local places.

**Comment by kiw1meister** [comment]
Backend issue
